import type {
  Project,
  ProtocolRun,
  StepRun,
  CodexRun,
  Event,
  PolicyPack,
  Clarification,
  QueueStats,
  OnboardingSummary,
  Branch,
  RunArtifact,
  PolicyFinding,
  Sprint,
  AgileTask,
} from "./types"

// =============================================================================
// Mock Projects
// =============================================================================

export const mockProjects: Project[] = [
  {
    id: 1,
    name: "tasksgodzilla-web",
    git_url: "https://github.com/acme/tasksgodzilla-web.git",
    local_path: "/workspace/tasksgodzilla-web",
    base_branch: "main",
    ci_provider: "github-actions",
    project_classification: "web-app",
    default_models: {
      planning: "openai/gpt-4",
      coding: "anthropic/claude-3.5-sonnet",
      review: "openai/gpt-4",
    },
    secrets: {},
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-01-20T14:22:00Z",
    policy_pack_key: "standard-v1",
    policy_pack_version: "1.2.0",
    policy_overrides: {},
    policy_repo_local_enabled: true,
    policy_effective_hash: "abc123def456",
    policy_enforcement_mode: "warn",
  },
  {
    id: 2,
    name: "api-gateway",
    git_url: "https://github.com/acme/api-gateway.git",
    local_path: "/workspace/api-gateway",
    base_branch: "develop",
    ci_provider: "gitlab-ci",
    project_classification: "backend-service",
    default_models: {
      planning: "anthropic/claude-3.5-sonnet",
      coding: "anthropic/claude-3.5-sonnet",
      review: "openai/gpt-4",
    },
    secrets: {},
    created_at: "2024-01-10T08:15:00Z",
    updated_at: "2024-01-22T09:45:00Z",
    policy_pack_key: "security-strict",
    policy_pack_version: "2.0.1",
    policy_overrides: null,
    policy_repo_local_enabled: false,
    policy_effective_hash: "def789ghi012",
    policy_enforcement_mode: "enforce",
  },
  {
    id: 3,
    name: "mobile-app",
    git_url: "https://github.com/acme/mobile-app.git",
    local_path: "/workspace/mobile-app",
    base_branch: "main",
    ci_provider: "circle-ci",
    project_classification: "mobile-app",
    default_models: {
      planning: "openai/gpt-4",
      coding: "anthropic/claude-3.5-sonnet",
      review: "openai/gpt-4-turbo",
    },
    secrets: {},
    created_at: "2024-01-05T12:00:00Z",
    updated_at: "2024-01-18T16:30:00Z",
    policy_pack_key: "standard-v1",
    policy_pack_version: "1.2.0",
    policy_overrides: { "security.tls_version": "1.3" },
    policy_repo_local_enabled: true,
    policy_effective_hash: "ghi345jkl678",
    policy_enforcement_mode: "warn",
  },
  {
    id: 4,
    name: "analytics-pipeline",
    git_url: "https://github.com/acme/analytics-pipeline.git",
    local_path: null,
    base_branch: "main",
    ci_provider: "jenkins",
    project_classification: "data-pipeline",
    default_models: null,
    secrets: {},
    created_at: "2024-01-12T14:20:00Z",
    updated_at: "2024-01-21T11:15:00Z",
    policy_pack_key: null,
    policy_pack_version: null,
    policy_overrides: null,
    policy_repo_local_enabled: null,
    policy_effective_hash: null,
    policy_enforcement_mode: null,
  },
]

// =============================================================================
// Mock Protocols
// =============================================================================

export const mockProtocols: ProtocolRun[] = [
  {
    id: 101,
    project_id: 1,
    protocol_name: "add-authentication",
    status: "running",
    base_branch: "main",
    worktree_path: "/workspace/tasksgodzilla-web/protocol-101",
    protocol_root: "protocols/add-authentication",
    description: "Implement user authentication with JWT tokens",
    template_config: { template: "auth-flow", features: ["jwt", "refresh-tokens"] },
    template_source: "templates/auth-flow.yaml",
    spec_hash: "spec-abc123",
    spec_validation_status: "valid",
    spec_validated_at: "2024-01-20T10:00:00Z",
    policy_pack_key: "standard-v1",
    policy_pack_version: "1.2.0",
    policy_effective_hash: "abc123def456",
    policy_effective_json: {},
    created_at: "2024-01-20T09:30:00Z",
    updated_at: "2024-01-20T14:22:00Z",
    project_name: "tasksgodzilla-web",
  },
  {
    id: 102,
    project_id: 1,
    protocol_name: "refactor-database-layer",
    status: "paused",
    base_branch: "main",
    worktree_path: "/workspace/tasksgodzilla-web/protocol-102",
    protocol_root: "protocols/refactor-database",
    description: "Migrate from raw SQL to Prisma ORM",
    template_config: { template: "database-migration" },
    template_source: "templates/db-migration.yaml",
    spec_hash: "spec-def456",
    spec_validation_status: "valid",
    spec_validated_at: "2024-01-19T15:30:00Z",
    policy_pack_key: "standard-v1",
    policy_pack_version: "1.2.0",
    policy_effective_hash: "abc123def456",
    policy_effective_json: {},
    created_at: "2024-01-19T14:00:00Z",
    updated_at: "2024-01-20T11:45:00Z",
    project_name: "tasksgodzilla-web",
  },
  {
    id: 103,
    project_id: 2,
    protocol_name: "implement-rate-limiting",
    status: "completed",
    base_branch: "develop",
    worktree_path: null,
    protocol_root: "protocols/rate-limiting",
    description: "Add Redis-based rate limiting to API endpoints",
    template_config: { template: "api-middleware" },
    template_source: "templates/middleware.yaml",
    spec_hash: "spec-ghi789",
    spec_validation_status: "valid",
    spec_validated_at: "2024-01-18T12:00:00Z",
    policy_pack_key: "security-strict",
    policy_pack_version: "2.0.1",
    policy_effective_hash: "def789ghi012",
    policy_effective_json: {},
    created_at: "2024-01-18T10:00:00Z",
    updated_at: "2024-01-19T16:30:00Z",
    project_name: "api-gateway",
  },
  {
    id: 104,
    project_id: 2,
    protocol_name: "add-graphql-support",
    status: "failed",
    base_branch: "develop",
    worktree_path: "/workspace/api-gateway/protocol-104",
    protocol_root: "protocols/graphql",
    description: "Add GraphQL endpoint alongside REST API",
    template_config: { template: "graphql-api" },
    template_source: "templates/graphql.yaml",
    spec_hash: "spec-jkl012",
    spec_validation_status: "invalid",
    spec_validated_at: "2024-01-20T08:00:00Z",
    policy_pack_key: "security-strict",
    policy_pack_version: "2.0.1",
    policy_effective_hash: "def789ghi012",
    policy_effective_json: {},
    created_at: "2024-01-20T07:00:00Z",
    updated_at: "2024-01-20T13:15:00Z",
    project_name: "api-gateway",
  },
  {
    id: 105,
    project_id: 3,
    protocol_name: "offline-mode-support",
    status: "blocked",
    base_branch: "main",
    worktree_path: "/workspace/mobile-app/protocol-105",
    protocol_root: "protocols/offline-mode",
    description: "Implement offline-first data sync with conflict resolution",
    template_config: { template: "offline-sync" },
    template_source: "templates/offline.yaml",
    spec_hash: "spec-mno345",
    spec_validation_status: "pending",
    spec_validated_at: null,
    policy_pack_key: "standard-v1",
    policy_pack_version: "1.2.0",
    policy_effective_hash: "ghi345jkl678",
    policy_effective_json: {},
    created_at: "2024-01-21T09:00:00Z",
    updated_at: "2024-01-21T14:00:00Z",
    project_name: "mobile-app",
  },
]

// =============================================================================
// Mock Steps
// =============================================================================

export const mockSteps: StepRun[] = [
  {
    id: 1001,
    protocol_run_id: 101,
    step_index: 0,
    step_name: "plan_architecture",
    step_type: "plan",
    status: "completed",
    retries: 0,
    model: "openai/gpt-4.1",
    engine_id: "planner-v2",
    policy: {},
    runtime_state: { loop_counts: {}, inline_trigger_depth: 0 },
    summary: "Designed JWT authentication flow with refresh token rotation",
    created_at: "2024-01-20T09:35:00Z",
    updated_at: "2024-01-20T10:15:00Z",
  },
  {
    id: 1002,
    protocol_run_id: 101,
    step_index: 1,
    step_name: "implement_auth_service",
    step_type: "code",
    status: "completed",
    retries: 1,
    model: "anthropic/claude-3.5-sonnet",
    engine_id: "coder-v3",
    policy: {},
    runtime_state: { loop_counts: { retry: 1 }, inline_trigger_depth: 0 },
    summary: "Created auth service with login, logout, and token refresh endpoints",
    created_at: "2024-01-20T10:20:00Z",
    updated_at: "2024-01-20T12:45:00Z",
  },
  {
    id: 1003,
    protocol_run_id: 101,
    step_index: 2,
    step_name: "add_middleware",
    step_type: "code",
    status: "running",
    retries: 0,
    model: "anthropic/claude-3.5-sonnet",
    engine_id: "coder-v3",
    policy: {},
    runtime_state: { loop_counts: {}, inline_trigger_depth: 0 },
    summary: null,
    created_at: "2024-01-20T12:50:00Z",
    updated_at: "2024-01-20T14:22:00Z",
  },
  {
    id: 1004,
    protocol_run_id: 101,
    step_index: 3,
    step_name: "write_tests",
    step_type: "test",
    status: "pending",
    retries: 0,
    model: null,
    engine_id: null,
    policy: {},
    runtime_state: null,
    summary: null,
    created_at: "2024-01-20T09:35:00Z",
    updated_at: "2024-01-20T09:35:00Z",
  },
]

// =============================================================================
// Mock Runs
// =============================================================================

export const mockRuns: CodexRun[] = [
  {
    run_id: "run_abc123def456",
    job_type: "step_executor",
    run_kind: "code",
    status: "succeeded",
    project_id: 1,
    protocol_run_id: 101,
    step_run_id: 1002,
    attempt: 1,
    worker_id: "worker-01",
    queue: "default",
    prompt_version: "v2.5",
    params: { step_name: "implement_auth_service", model: "anthropic/claude-3.5-sonnet" },
    result: { files_modified: 5, tests_added: 8 },
    error: null,
    log_path: "/logs/run_abc123def456.log",
    cost_tokens: 15420,
    cost_cents: 18,
    started_at: "2024-01-20T10:20:00Z",
    finished_at: "2024-01-20T12:45:00Z",
    created_at: "2024-01-20T10:19:00Z",
  },
  {
    run_id: "run_def456ghi789",
    job_type: "step_executor",
    run_kind: "plan",
    status: "succeeded",
    project_id: 1,
    protocol_run_id: 101,
    step_run_id: 1001,
    attempt: 1,
    worker_id: "worker-02",
    queue: "default",
    prompt_version: "v2.5",
    params: { step_name: "plan_architecture", model: "openai/gpt-4.1" },
    result: { plan_generated: true, components: 3 },
    error: null,
    log_path: "/logs/run_def456ghi789.log",
    cost_tokens: 8200,
    cost_cents: 12,
    started_at: "2024-01-20T09:35:00Z",
    finished_at: "2024-01-20T10:15:00Z",
    created_at: "2024-01-20T09:34:00Z",
  },
  {
    run_id: "run_ghi789jkl012",
    job_type: "onboarding",
    run_kind: "onboarding",
    status: "running",
    project_id: 4,
    protocol_run_id: null,
    step_run_id: null,
    attempt: 1,
    worker_id: "worker-03",
    queue: "onboarding",
    prompt_version: "v2.4",
    params: { project_id: 4 },
    result: null,
    error: null,
    log_path: "/logs/run_ghi789jkl012.log",
    cost_tokens: null,
    cost_cents: null,
    started_at: "2024-01-21T11:20:00Z",
    finished_at: null,
    created_at: "2024-01-21T11:19:00Z",
  },
  {
    run_id: "run_jkl012mno345",
    job_type: "step_executor",
    run_kind: "code",
    status: "failed",
    project_id: 2,
    protocol_run_id: 104,
    step_run_id: 1005,
    attempt: 2,
    worker_id: "worker-01",
    queue: "default",
    prompt_version: "v2.5",
    params: { step_name: "setup_graphql_schema", model: "anthropic/claude-3.5-sonnet" },
    result: null,
    error: "PolicyViolationError: Schema complexity exceeds limit",
    log_path: "/logs/run_jkl012mno345.log",
    cost_tokens: 12400,
    cost_cents: 15,
    started_at: "2024-01-20T12:00:00Z",
    finished_at: "2024-01-20T13:15:00Z",
    created_at: "2024-01-20T11:59:00Z",
  },
]

// =============================================================================
// Mock Events
// =============================================================================

export const mockEvents: Event[] = [
  {
    id: 5001,
    protocol_run_id: 101,
    step_run_id: 1003,
    event_type: "step.started",
    message: "Started step: add_middleware",
    metadata: { step_index: 2 },
    created_at: "2024-01-20T12:50:00Z",
    protocol_name: "add-authentication",
    project_id: 1,
    project_name: "tasksgodzilla-web",
  },
  {
    id: 5002,
    protocol_run_id: 101,
    step_run_id: 1002,
    event_type: "step.completed",
    message: "Completed step: implement_auth_service",
    metadata: { duration_seconds: 8100 },
    created_at: "2024-01-20T12:45:00Z",
    protocol_name: "add-authentication",
    project_id: 1,
    project_name: "tasksgodzilla-web",
  },
  {
    id: 5003,
    protocol_run_id: 104,
    step_run_id: 1005,
    event_type: "step.failed",
    message: "Step failed: setup_graphql_schema",
    metadata: { error: "PolicyViolationError", retry_count: 2 },
    created_at: "2024-01-20T13:15:00Z",
    protocol_name: "add-graphql-support",
    project_id: 2,
    project_name: "api-gateway",
  },
  {
    id: 5004,
    protocol_run_id: 103,
    step_run_id: null,
    event_type: "protocol.completed",
    message: "Protocol completed successfully",
    metadata: { duration_hours: 6.5, steps_completed: 4 },
    created_at: "2024-01-19T16:30:00Z",
    protocol_name: "implement-rate-limiting",
    project_id: 2,
    project_name: "api-gateway",
  },
  {
    id: 5005,
    protocol_run_id: 105,
    step_run_id: null,
    event_type: "protocol.blocked",
    message: "Protocol blocked: Awaiting clarification",
    metadata: { clarification_id: 7001 },
    created_at: "2024-01-21T14:00:00Z",
    protocol_name: "offline-mode-support",
    project_id: 3,
    project_name: "mobile-app",
  },
]

// =============================================================================
// Mock Policy Packs
// =============================================================================

export const mockPolicyPacks: PolicyPack[] = [
  {
    id: 1,
    key: "standard-v1",
    version: "1.2.0",
    name: "Standard Development Policy",
    description: "Default policy pack for typical web applications",
    status: "active",
    pack: {
      meta: { author: "Platform Team", last_updated: "2024-01-15" },
      defaults: { max_file_size: 5000, require_tests: true },
      requirements: { typescript: true, linting: "eslint" },
      clarifications: {},
      enforcement: { mode: "warn" },
    },
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    key: "security-strict",
    version: "2.0.1",
    name: "Strict Security Policy",
    description: "Enhanced security requirements for production services",
    status: "active",
    pack: {
      meta: { author: "Security Team", compliance: "SOC2" },
      defaults: { require_auth: true, tls_min_version: "1.3" },
      requirements: {
        vulnerability_scanning: true,
        dependency_review: true,
        secret_detection: true,
      },
      clarifications: {},
      enforcement: { mode: "enforce", break_on_error: true },
    },
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: 3,
    key: "experimental",
    version: "0.5.0",
    name: "Experimental Features",
    description: "Policy pack for testing new AI capabilities",
    status: "draft",
    pack: {
      meta: { author: "AI Research", experimental: true },
      defaults: { allow_auto_merge: false },
      requirements: {},
      clarifications: {},
      enforcement: { mode: "off" },
    },
    created_at: "2024-01-20T00:00:00Z",
  },
]

// =============================================================================
// Mock Clarifications
// =============================================================================

export const mockClarifications: Clarification[] = [
  {
    id: 7001,
    scope: "protocol",
    project_id: 3,
    protocol_run_id: 105,
    step_run_id: null,
    key: "offline_sync_strategy",
    question: "Which conflict resolution strategy should be used for offline sync?",
    recommended: "last_write_wins",
    options: ["last_write_wins", "manual_review", "custom_merge"],
    applies_to: "offline-mode-support",
    blocking: true,
    answer: null,
    status: "open",
    answered_at: null,
    answered_by: null,
  },
  {
    id: 7002,
    scope: "step",
    project_id: 1,
    protocol_run_id: 102,
    step_run_id: 1006,
    key: "orm_migration_approach",
    question: "Should we migrate incrementally or do a full rewrite?",
    recommended: "incremental",
    options: ["incremental", "full_rewrite"],
    applies_to: "refactor-database-layer",
    blocking: false,
    answer: "incremental",
    status: "answered",
    answered_at: "2024-01-20T11:45:00Z",
    answered_by: "user@example.com",
  },
  {
    id: 7003,
    scope: "project",
    project_id: 4,
    protocol_run_id: null,
    step_run_id: null,
    key: "data_retention_policy",
    question: "What is the data retention period for analytics data?",
    recommended: "90_days",
    options: ["30_days", "90_days", "365_days", "indefinite"],
    applies_to: null,
    blocking: true,
    answer: null,
    status: "open",
    answered_at: null,
    answered_by: null,
  },
]

// =============================================================================
// Mock Queue Stats
// =============================================================================

export const mockQueueStats: QueueStats[] = [
  { name: "default", queued: 12, started: 5, failed: 2 },
  { name: "onboarding", queued: 1, started: 1, failed: 0 },
  { name: "high_priority", queued: 0, started: 2, failed: 0 },
  { name: "low_priority", queued: 8, started: 0, failed: 1 },
]

// =============================================================================
// Mock Onboarding
// =============================================================================

export const mockOnboarding: Record<number, OnboardingSummary> = {
  4: {
    project_id: 4,
    status: "running",
    stages: [
      {
        name: "clone_repo",
        status: "completed",
        started_at: "2024-01-21T11:20:00Z",
        completed_at: "2024-01-21T11:22:00Z",
      },
      {
        name: "analyze_structure",
        status: "running",
        started_at: "2024-01-21T11:22:00Z",
        completed_at: null,
      },
      {
        name: "generate_config",
        status: "pending",
        started_at: null,
        completed_at: null,
      },
      {
        name: "validate_setup",
        status: "pending",
        started_at: null,
        completed_at: null,
      },
    ],
    events: [
      {
        event_type: "onboarding.started",
        message: "Onboarding started for analytics-pipeline",
        created_at: "2024-01-21T11:20:00Z",
      },
      {
        event_type: "onboarding.stage_completed",
        message: "Repository cloned successfully",
        created_at: "2024-01-21T11:22:00Z",
      },
    ],
    blocking_clarifications: 1,
  },
}

// =============================================================================
// Mock Branches
// =============================================================================

export const mockBranches: Record<number, Branch[]> = {
  1: [
    { name: "main", sha: "abc123", is_remote: true },
    { name: "develop", sha: "def456", is_remote: true },
    { name: "feature/new-ui", sha: "ghi789", is_remote: false },
  ],
  2: [
    { name: "develop", sha: "jkl012", is_remote: true },
    { name: "staging", sha: "mno345", is_remote: true },
  ],
}

// =============================================================================
// Mock Artifacts
// =============================================================================

export const mockArtifacts: Record<string, RunArtifact[]> = {
  run_abc123def456: [
    {
      id: 1,
      run_id: "run_abc123def456",
      name: "auth-service.ts",
      kind: "source",
      path: "/src/services/auth-service.ts",
      sha256: "abc123",
      bytes: 4532,
      created_at: "2024-01-20T12:45:00Z",
      content_type: "file",
    },
    {
      id: 2,
      run_id: "run_abc123def456",
      name: "auth.test.ts",
      kind: "test",
      path: "/tests/auth.test.ts",
      sha256: "def456",
      bytes: 2103,
      created_at: "2024-01-20T12:45:00Z",
      content_type: "file",
    },
    {
      id: 3,
      run_id: "run_abc123def456",
      name: "auth-service.ts.diff",
      kind: "diff",
      path: "/src/services/auth-service.ts",
      sha256: "ghi789",
      bytes: 1254,
      created_at: "2024-01-20T12:46:00Z",
      content_type: "diff",
      diff_data: {
        old_path: "src/services/auth-service.ts",
        new_path: "src/services/auth-service.ts",
        additions: 12,
        deletions: 5,
        hunks: [
          {
            old_start: 15,
            old_lines: 8,
            new_start: 15,
            new_lines: 15,
            lines: [
              {
                type: "context",
                content: "  async authenticate(token: string) {",
                old_line_number: 15,
                new_line_number: 15,
              },
              { type: "delete", content: "    if (!token) {", old_line_number: 16 },
              { type: "delete", content: "      throw new Error('Token required');", old_line_number: 17 },
              { type: "delete", content: "    }", old_line_number: 18 },
              { type: "add", content: "    // Validate token format", new_line_number: 16 },
              { type: "add", content: "    if (!token || token.length === 0) {", new_line_number: 17 },
              { type: "add", content: "      throw new AuthError('Token is required');", new_line_number: 18 },
              { type: "add", content: "    }", new_line_number: 19 },
              { type: "add", content: "", new_line_number: 20 },
              { type: "add", content: "    // Decode and verify JWT", new_line_number: 21 },
              {
                type: "context",
                content: "    const decoded = jwt.verify(token, secret);",
                old_line_number: 19,
                new_line_number: 22,
              },
              { type: "add", content: "    ", new_line_number: 23 },
              { type: "add", content: "    // Check token expiration", new_line_number: 24 },
              { type: "add", content: "    if (decoded.exp < Date.now() / 1000) {", new_line_number: 25 },
              { type: "add", content: "      throw new AuthError('Token expired');", new_line_number: 26 },
              { type: "add", content: "    }", new_line_number: 27 },
              { type: "context", content: "    return decoded;", old_line_number: 20, new_line_number: 28 },
              { type: "context", content: "  }", old_line_number: 21, new_line_number: 29 },
            ],
          },
        ],
      },
    },
    {
      id: 4,
      run_id: "run_abc123def456",
      name: "user-model.ts.diff",
      kind: "diff",
      path: "/src/models/user-model.ts",
      sha256: "jkl012",
      bytes: 876,
      created_at: "2024-01-20T12:46:00Z",
      content_type: "diff",
      diff_data: {
        old_path: "src/models/user-model.ts",
        new_path: "src/models/user-model.ts",
        additions: 8,
        deletions: 2,
        hunks: [
          {
            old_start: 42,
            old_lines: 6,
            new_start: 42,
            new_lines: 12,
            lines: [
              { type: "context", content: "export interface User {", old_line_number: 42, new_line_number: 42 },
              { type: "context", content: "  id: string;", old_line_number: 43, new_line_number: 43 },
              { type: "context", content: "  email: string;", old_line_number: 44, new_line_number: 44 },
              { type: "delete", content: "  name: string;", old_line_number: 45 },
              { type: "add", content: "  firstName: string;", new_line_number: 45 },
              { type: "add", content: "  lastName: string;", new_line_number: 46 },
              { type: "add", content: "  displayName: string;", new_line_number: 47 },
              { type: "context", content: "  role: UserRole;", old_line_number: 46, new_line_number: 48 },
              { type: "add", content: "  permissions: string[];", new_line_number: 49 },
              { type: "add", content: "  settings: UserSettings;", new_line_number: 50 },
              { type: "delete", content: "  isActive: boolean;", old_line_number: 47 },
              { type: "add", content: "  status: 'active' | 'inactive' | 'suspended';", new_line_number: 51 },
              { type: "add", content: "  createdAt: Date;", new_line_number: 52 },
              { type: "add", content: "  updatedAt: Date;", new_line_number: 53 },
              { type: "context", content: "}", old_line_number: 48, new_line_number: 54 },
            ],
          },
        ],
      },
    },
  ],
}

// =============================================================================
// Mock Policy Findings
// =============================================================================

export const mockPolicyFindings: Record<number, PolicyFinding[]> = {
  104: [
    {
      code: "SEC-001",
      severity: "error",
      message: "GraphQL schema complexity exceeds allowed limit (max: 100, found: 145)",
      location: "schema/schema.graphql:15",
      suggested_fix: "Reduce query depth or implement query complexity limits",
    },
    {
      code: "PERF-002",
      severity: "warning",
      message: "N+1 query detected in resolver",
      location: "resolvers/user.resolver.ts:42",
      suggested_fix: "Use DataLoader to batch database queries",
    },
  ],
  105: [
    {
      code: "DATA-003",
      severity: "info",
      message: "Offline storage not encrypted",
      location: "storage/offline-store.ts:28",
      suggested_fix: "Consider using encrypted storage for sensitive data",
    },
  ],
}

// =============================================================================
// Mock Sprints
// =============================================================================

export const mockSprints: Sprint[] = [
  {
    id: 1,
    project_id: 1,
    name: "Sprint 1 - Authentication Foundation",
    goal: "Implement core authentication system with JWT tokens and user management",
    status: "active",
    start_date: "2024-01-15T00:00:00Z",
    end_date: "2024-01-29T00:00:00Z",
    created_at: "2024-01-15T09:00:00Z",
    updated_at: "2024-01-20T14:22:00Z",
  },
  {
    id: 2,
    project_id: 1,
    name: "Sprint 2 - Database Migration",
    goal: "Complete database layer refactoring with Prisma ORM",
    status: "planned",
    start_date: "2024-01-29T00:00:00Z",
    end_date: "2024-02-12T00:00:00Z",
    created_at: "2024-01-18T10:00:00Z",
    updated_at: "2024-01-20T11:00:00Z",
  },
  {
    id: 3,
    project_id: 2,
    name: "Sprint 3 - API Enhancements",
    goal: "Add rate limiting and GraphQL support to API gateway",
    status: "completed",
    start_date: "2024-01-08T00:00:00Z",
    end_date: "2024-01-22T00:00:00Z",
    created_at: "2024-01-08T08:00:00Z",
    updated_at: "2024-01-22T17:00:00Z",
  },
  {
    id: 4,
    project_id: 3,
    name: "Sprint 4 - Offline Mode",
    goal: "Implement offline-first architecture with sync capabilities",
    status: "active",
    start_date: "2024-01-22T00:00:00Z",
    end_date: "2024-02-05T00:00:00Z",
    created_at: "2024-01-22T09:00:00Z",
    updated_at: "2024-01-23T14:00:00Z",
  },
]

// =============================================================================
// Mock Agile Tasks
// =============================================================================

export const mockAgileTasks: AgileTask[] = [
  // Project 1 - Sprint 1 (Active)
  {
    id: 1,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: 101,
    step_run_id: 1001,
    title: "Design JWT authentication architecture",
    description: "Create detailed architecture for JWT-based authentication with refresh token rotation",
    task_type: "story",
    board_status: "done",
    priority: "high",
    story_points: 5,
    assignee: "alice@example.com",
    labels: ["authentication", "security"],
    acceptance_criteria: [
      "JWT token structure defined",
      "Refresh token mechanism designed",
      "Token expiration strategy documented",
    ],
    due_date: "2024-01-18T00:00:00Z",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-18T16:30:00Z",
  },
  {
    id: 2,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: 101,
    step_run_id: 1002,
    title: "Implement auth service endpoints",
    description: "Build login, logout, refresh token, and password reset endpoints",
    task_type: "story",
    board_status: "done",
    priority: "high",
    story_points: 8,
    assignee: "bob@example.com",
    labels: ["authentication", "backend"],
    acceptance_criteria: [
      "Login endpoint functional",
      "Logout invalidates tokens",
      "Refresh token rotation working",
      "Password reset flow complete",
    ],
    due_date: "2024-01-22T00:00:00Z",
    created_at: "2024-01-15T10:15:00Z",
    updated_at: "2024-01-20T12:45:00Z",
  },
  {
    id: 3,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: 101,
    step_run_id: 1003,
    title: "Add authentication middleware",
    description: "Create Express middleware for protecting routes with JWT verification",
    task_type: "story",
    board_status: "in_progress",
    priority: "high",
    story_points: 3,
    assignee: "bob@example.com",
    labels: ["authentication", "middleware"],
    acceptance_criteria: [
      "Middleware validates JWT tokens",
      "Protected routes are secured",
      "Error handling implemented",
    ],
    due_date: "2024-01-24T00:00:00Z",
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-01-20T14:22:00Z",
  },
  {
    id: 4,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: 101,
    step_run_id: 1004,
    title: "Write comprehensive auth tests",
    description: "Create unit and integration tests for authentication system",
    task_type: "task",
    board_status: "review",
    priority: "high",
    story_points: 5,
    assignee: "charlie@example.com",
    labels: ["testing", "authentication"],
    acceptance_criteria: ["Unit tests for auth service", "Integration tests for endpoints", "Test coverage > 80%"],
    due_date: "2024-01-26T00:00:00Z",
    created_at: "2024-01-15T10:45:00Z",
    updated_at: "2024-01-23T11:00:00Z",
  },
  {
    id: 5,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: null,
    step_run_id: null,
    title: "Update API documentation",
    description: "Document all authentication endpoints in Swagger/OpenAPI",
    task_type: "task",
    board_status: "testing",
    priority: "medium",
    story_points: 2,
    assignee: "alice@example.com",
    labels: ["documentation", "api"],
    acceptance_criteria: ["OpenAPI spec updated", "Example requests provided", "Error responses documented"],
    due_date: "2024-01-27T00:00:00Z",
    created_at: "2024-01-16T09:00:00Z",
    updated_at: "2024-01-24T15:30:00Z",
  },
  {
    id: 6,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: null,
    step_run_id: null,
    title: "Implement rate limiting for auth endpoints",
    description: "Add rate limiting to prevent brute force attacks on login",
    task_type: "story",
    board_status: "todo",
    priority: "high",
    story_points: 3,
    assignee: "david@example.com",
    labels: ["security", "authentication"],
    acceptance_criteria: ["Rate limits configured", "Lockout mechanism implemented", "Rate limit headers returned"],
    due_date: "2024-01-28T00:00:00Z",
    created_at: "2024-01-17T11:00:00Z",
    updated_at: "2024-01-20T09:15:00Z",
  },

  // Project 1 - Sprint 2 (Planned)
  {
    id: 7,
    project_id: 1,
    sprint_id: 2,
    protocol_run_id: 102,
    step_run_id: null,
    title: "Set up Prisma schema",
    description: "Define database schema using Prisma ORM",
    task_type: "story",
    board_status: "backlog",
    priority: "high",
    story_points: 5,
    assignee: "alice@example.com",
    labels: ["database", "prisma"],
    acceptance_criteria: ["Schema matches current DB", "Relationships defined", "Migrations configured"],
    due_date: null,
    created_at: "2024-01-18T10:00:00Z",
    updated_at: "2024-01-18T10:00:00Z",
  },
  {
    id: 8,
    project_id: 1,
    sprint_id: 2,
    protocol_run_id: 102,
    step_run_id: null,
    title: "Migrate user queries to Prisma",
    description: "Replace raw SQL user queries with Prisma client",
    task_type: "story",
    board_status: "backlog",
    priority: "medium",
    story_points: 8,
    assignee: null,
    labels: ["database", "migration"],
    acceptance_criteria: ["All user queries migrated", "Tests passing", "Performance maintained"],
    due_date: null,
    created_at: "2024-01-18T10:15:00Z",
    updated_at: "2024-01-18T10:15:00Z",
  },

  // Project 2 - Sprint 3 (Completed)
  {
    id: 9,
    project_id: 2,
    sprint_id: 3,
    protocol_run_id: 103,
    step_run_id: null,
    title: "Implement Redis rate limiting",
    description: "Add Redis-based rate limiting middleware to API gateway",
    task_type: "story",
    board_status: "done",
    priority: "high",
    story_points: 5,
    assignee: "eve@example.com",
    labels: ["performance", "redis", "middleware"],
    acceptance_criteria: [
      "Redis connection configured",
      "Rate limits enforced per endpoint",
      "Rate limit headers returned",
    ],
    due_date: "2024-01-18T00:00:00Z",
    created_at: "2024-01-08T10:00:00Z",
    updated_at: "2024-01-18T16:30:00Z",
  },
  {
    id: 10,
    project_id: 2,
    sprint_id: 3,
    protocol_run_id: 104,
    step_run_id: 1005,
    title: "Design GraphQL schema",
    description: "Create GraphQL schema for API endpoints",
    task_type: "story",
    board_status: "done",
    priority: "medium",
    story_points: 8,
    assignee: "frank@example.com",
    labels: ["graphql", "api"],
    acceptance_criteria: ["Schema defined", "Queries implemented", "Mutations implemented"],
    due_date: "2024-01-20T00:00:00Z",
    created_at: "2024-01-08T10:30:00Z",
    updated_at: "2024-01-20T13:15:00Z",
  },
  {
    id: 11,
    project_id: 2,
    sprint_id: 3,
    protocol_run_id: 104,
    step_run_id: null,
    title: "Fix GraphQL complexity issues",
    description: "Resolve policy violations for GraphQL schema complexity",
    task_type: "bug",
    board_status: "done",
    priority: "critical",
    story_points: 3,
    assignee: "frank@example.com",
    labels: ["graphql", "bugfix", "security"],
    acceptance_criteria: ["Complexity reduced", "Policy checks passing", "Tests updated"],
    due_date: "2024-01-21T00:00:00Z",
    created_at: "2024-01-20T14:00:00Z",
    updated_at: "2024-01-21T11:30:00Z",
  },

  // Project 3 - Sprint 4 (Active)
  {
    id: 12,
    project_id: 3,
    sprint_id: 4,
    protocol_run_id: 105,
    step_run_id: null,
    title: "Design offline storage architecture",
    description: "Define data sync strategy and conflict resolution approach",
    task_type: "story",
    board_status: "in_progress",
    priority: "high",
    story_points: 8,
    assignee: "grace@example.com",
    labels: ["offline", "architecture"],
    acceptance_criteria: ["Sync strategy documented", "Conflict resolution defined", "Storage structure designed"],
    due_date: "2024-01-25T00:00:00Z",
    created_at: "2024-01-22T09:00:00Z",
    updated_at: "2024-01-23T14:00:00Z",
  },
  {
    id: 13,
    project_id: 3,
    sprint_id: 4,
    protocol_run_id: 105,
    step_run_id: null,
    title: "Implement local data store",
    description: "Create IndexedDB wrapper for offline data storage",
    task_type: "story",
    board_status: "todo",
    priority: "high",
    story_points: 5,
    assignee: "henry@example.com",
    labels: ["offline", "storage"],
    acceptance_criteria: ["IndexedDB configured", "CRUD operations implemented", "Encryption added"],
    due_date: "2024-01-30T00:00:00Z",
    created_at: "2024-01-22T09:15:00Z",
    updated_at: "2024-01-22T09:15:00Z",
  },
  {
    id: 14,
    project_id: 3,
    sprint_id: 4,
    protocol_run_id: null,
    step_run_id: null,
    title: "Build sync queue manager",
    description: "Create queue system for synchronizing offline changes",
    task_type: "story",
    board_status: "todo",
    priority: "medium",
    story_points: 5,
    assignee: null,
    labels: ["offline", "sync"],
    acceptance_criteria: ["Queue persists changes", "Retry logic implemented", "Conflict detection working"],
    due_date: "2024-02-02T00:00:00Z",
    created_at: "2024-01-22T09:30:00Z",
    updated_at: "2024-01-22T09:30:00Z",
  },
  {
    id: 15,
    project_id: 3,
    sprint_id: 4,
    protocol_run_id: null,
    step_run_id: null,
    title: "Add offline status indicator",
    description: "Show users when app is in offline mode",
    task_type: "task",
    board_status: "backlog",
    priority: "low",
    story_points: 2,
    assignee: null,
    labels: ["ui", "offline"],
    acceptance_criteria: ["Indicator visible when offline", "Connection status tracked", "UI updates on reconnect"],
    due_date: null,
    created_at: "2024-01-22T10:00:00Z",
    updated_at: "2024-01-22T10:00:00Z",
  },

  // Backlog tasks (no sprint)
  {
    id: 16,
    project_id: 1,
    sprint_id: null,
    protocol_run_id: null,
    step_run_id: null,
    title: "Add social login (OAuth)",
    description: "Support Google, GitHub, and Microsoft OAuth providers",
    task_type: "story",
    board_status: "backlog",
    priority: "medium",
    story_points: 8,
    assignee: null,
    labels: ["authentication", "oauth"],
    acceptance_criteria: ["OAuth flow implemented", "Provider integration complete", "User linking working"],
    due_date: null,
    created_at: "2024-01-16T14:00:00Z",
    updated_at: "2024-01-16T14:00:00Z",
  },
  {
    id: 17,
    project_id: 1,
    sprint_id: null,
    protocol_run_id: null,
    step_run_id: null,
    title: "Implement 2FA support",
    description: "Add two-factor authentication with TOTP",
    task_type: "story",
    board_status: "backlog",
    priority: "medium",
    story_points: 5,
    assignee: null,
    labels: ["authentication", "security"],
    acceptance_criteria: ["TOTP generation working", "2FA setup flow complete", "Recovery codes generated"],
    due_date: null,
    created_at: "2024-01-17T10:00:00Z",
    updated_at: "2024-01-17T10:00:00Z",
  },
  {
    id: 18,
    project_id: 2,
    sprint_id: null,
    protocol_run_id: null,
    step_run_id: null,
    title: "Add WebSocket support",
    description: "Implement real-time updates using WebSockets",
    task_type: "story",
    board_status: "backlog",
    priority: "low",
    story_points: 8,
    assignee: null,
    labels: ["real-time", "websockets"],
    acceptance_criteria: [
      "WebSocket server running",
      "Client subscriptions working",
      "Message broadcasting functional",
    ],
    due_date: null,
    created_at: "2024-01-15T11:00:00Z",
    updated_at: "2024-01-15T11:00:00Z",
  },
  {
    id: 19,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: 101,
    step_run_id: 1003,
    title: "Add password strength validation",
    description: "Implement client and server-side password validation with strength meter",
    task_type: "task",
    board_status: "in_progress",
    priority: "medium",
    story_points: 3,
    assignee: "alice@example.com",
    labels: ["authentication", "frontend", "validation"],
    acceptance_criteria: [
      "Password strength meter UI implemented",
      "Server validation matches client rules",
      "Error messages are user-friendly",
    ],
    due_date: "2024-01-25T00:00:00Z",
    created_at: "2024-01-16T09:00:00Z",
    updated_at: "2024-01-20T10:15:00Z",
  },
  {
    id: 20,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: 101,
    step_run_id: 1003,
    title: "Fix token refresh race condition",
    description: "Handle concurrent requests during token refresh to prevent 401 errors",
    task_type: "bug",
    board_status: "review",
    priority: "critical",
    story_points: 2,
    assignee: "bob@example.com",
    labels: ["authentication", "bug", "critical"],
    acceptance_criteria: ["No 401 errors during refresh", "Concurrent requests queued properly"],
    due_date: "2024-01-20T00:00:00Z",
    created_at: "2024-01-17T11:00:00Z",
    updated_at: "2024-01-19T16:00:00Z",
  },
  {
    id: 21,
    project_id: 1,
    sprint_id: 1,
    protocol_run_id: null,
    step_run_id: null,
    title: "Research OAuth2 providers integration",
    description: "Investigate integration patterns for Google, GitHub, and Microsoft OAuth",
    task_type: "spike",
    board_status: "todo",
    priority: "low",
    story_points: 2,
    assignee: null,
    labels: ["authentication", "research", "oauth"],
    acceptance_criteria: ["Document pros/cons of each provider", "Recommend implementation approach"],
    due_date: "2024-01-28T00:00:00Z",
    created_at: "2024-01-17T14:00:00Z",
    updated_at: "2024-01-17T14:00:00Z",
  },
  // Project 1 - Sprint 2 (Planned)
  {
    id: 22,
    project_id: 1,
    sprint_id: 2,
    protocol_run_id: null,
    step_run_id: null,
    title: "Setup Prisma schema",
    description: "Define complete database schema with Prisma ORM",
    task_type: "story",
    board_status: "todo",
    priority: "high",
    story_points: 5,
    assignee: null,
    labels: ["database", "prisma"],
    acceptance_criteria: ["All entities modeled", "Relations defined", "Migrations created"],
    created_at: "2024-01-18T10:30:00Z",
    updated_at: "2024-01-18T10:30:00Z",
  },
  {
    id: 23,
    project_id: 1,
    sprint_id: 2,
    protocol_run_id: null,
    step_run_id: null,
    title: "Migrate existing data to Prisma",
    description: "Write and test data migration scripts from old schema to Prisma",
    task_type: "task",
    board_status: "backlog",
    priority: "medium",
    story_points: 8,
    assignee: null,
    labels: ["database", "migration"],
    acceptance_criteria: ["Zero data loss", "All relationships preserved", "Rollback plan tested"],
    created_at: "2024-01-18T10:45:00Z",
    updated_at: "2024-01-18T10:45:00Z",
  },
  // Project 2 - Sprint 3 (Completed)
  {
    id: 24,
    project_id: 2,
    sprint_id: 3,
    protocol_run_id: 201,
    step_run_id: null,
    title: "Implement rate limiting middleware",
    description: "Add configurable rate limiting to all API endpoints",
    task_type: "story",
    board_status: "done",
    priority: "high",
    story_points: 5,
    assignee: "charlie@example.com",
    labels: ["api", "security", "performance"],
    acceptance_criteria: ["Rate limits configurable per endpoint", "Proper 429 responses", "Redis-backed counter"],
    created_at: "2024-01-08T09:00:00Z",
    updated_at: "2024-01-15T14:00:00Z",
  },
  {
    id: 25,
    project_id: 2,
    sprint_id: 3,
    protocol_run_id: null,
    step_run_id: null,
    title: "Add GraphQL gateway",
    description: "Implement GraphQL layer on top of REST API",
    task_type: "story",
    board_status: "done",
    priority: "medium",
    story_points: 13,
    assignee: "dana@example.com",
    labels: ["api", "graphql", "gateway"],
    acceptance_criteria: ["All REST endpoints exposed via GraphQL", "Schema stitching working", "Query optimization"],
    created_at: "2024-01-08 09:30:00Z",
    updated_at: "2024-01-20T16:00:00Z",
  },
  {
    id: 26,
    project_id: 2,
    sprint_id: 3,
    protocol_run_id: 104,
    step_run_id: null,
    title: "Fix GraphQL N+1 query problem",
    description: "Optimize data loader to prevent N+1 queries in nested resolvers",
    task_type: "bug",
    board_status: "done",
    priority: "high",
    story_points: 3,
    assignee: "dana@example.com",
    labels: ["graphql", "performance", "bug"],
    acceptance_criteria: ["DataLoader implemented", "Query count reduced by 80%"],
    created_at: "2024-01-12T10:00:00Z",
    updated_at: "2024-01-18T12:00:00Z",
  },
  // Project 3 - Sprint 4 (Active)
  {
    id: 27,
    project_id: 3,
    sprint_id: 4,
    protocol_run_id: 105,
    step_run_id: null,
    title: "Design offline storage architecture",
    description: "Design client-side storage strategy with IndexedDB",
    task_type: "story",
    board_status: "done",
    priority: "critical",
    story_points: 8,
    assignee: "eve@example.com",
    labels: ["offline", "architecture", "storage"],
    acceptance_criteria: ["Storage schema defined", "Sync strategy documented", "Conflict resolution designed"],
    created_at: "2024-01-22T09:30:00Z",
    updated_at: "2024-01-24T15:00:00Z",
  },
  {
    id: 28,
    project_id: 3,
    sprint_id: 4,
    protocol_run_id: null,
    step_run_id: null,
    title: "Implement service worker for offline mode",
    description: "Build service worker with caching strategies and background sync",
    task_type: "story",
    board_status: "in_progress",
    priority: "high",
    story_points: 13,
    assignee: "frank@example.com",
    labels: ["offline", "service-worker", "pwa"],
    acceptance_criteria: ["Assets cached properly", "Background sync working", "Offline fallback page"],
    due_date: "2024-01-30T00:00:00Z",
    created_at: "2024-01-22T10:00:00Z",
    updated_at: "2024-01-24T11:30:00Z",
  },
  {
    id: 29,
    project_id: 3,
    sprint_id: 4,
    protocol_run_id: null,
    step_run_id: null,
    title: "Add conflict resolution UI",
    description: "Build UI for users to resolve data conflicts from offline changes",
    task_type: "story",
    board_status: "todo",
    priority: "medium",
    story_points: 5,
    assignee: null,
    labels: ["offline", "ui", "conflict-resolution"],
    acceptance_criteria: ["Conflicts clearly displayed", "User can choose resolution", "Auto-merge when possible"],
    due_date: "2024-02-02T00:00:00Z",
    created_at: "2024-01-22T11:00:00Z",
    updated_at: "2024-01-22T11:00:00Z",
  },
  {
    id: 30,
    project_id: 3,
    sprint_id: 4,
    protocol_run_id: null,
    step_run_id: null,
    title: "Service worker not updating on deployment",
    description: "Fix issue where service worker caches old version after deployment",
    task_type: "bug",
    board_status: "testing",
    priority: "critical",
    story_points: 2,
    assignee: "frank@example.com",
    labels: ["offline", "service-worker", "bug"],
    acceptance_criteria: ["New version deployed immediately", "Users notified of updates"],
    due_date: "2024-01-26T00:00:00Z",
    created_at: "2024-01-23T09:00:00Z",
    updated_at: "2024-01-24T16:00:00Z",
  },
  // Backlog tasks (no sprint assigned)
  {
    id: 15,
    project_id: 1,
    title: "Add two-factor authentication",
    description: "Implement TOTP-based 2FA for enhanced security",
    task_type: "story",
    board_status: "backlog",
    priority: "medium",
    story_points: 8,
    labels: ["authentication", "security", "2fa"],
    acceptance_criteria: ["TOTP generation working", "QR code displayed", "Backup codes provided"],
    created_at: "2024-01-19T14:00:00Z",
    updated_at: "2024-01-19T14:00:00Z",
  },
  {
    id: 16,
    project_id: 2,
    title: "Add WebSocket support to API",
    description: "Enable real-time updates via WebSocket connections",
    task_type: "story",
    board_status: "backlog",
    priority: "low",
    story_points: 13,
    labels: ["api", "websocket", "realtime"],
    acceptance_criteria: ["WebSocket server setup", "Authentication working", "Message broadcasting"],
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-01-20T10:00:00Z",
  },
  {
    id: 17,
    project_id: 3,
    title: "Research progressive web app features",
    description: "Investigate PWA capabilities for mobile app experience",
    task_type: "spike",
    board_status: "backlog",
    priority: "low",
    story_points: 3,
    labels: ["pwa", "research", "mobile"],
    acceptance_criteria: ["Document PWA features", "Assess feasibility", "Recommend implementation"],
    created_at: "2024-01-21T13:00:00Z",
    updated_at: "2024-01-21T13:00:00Z",
  },
  {
    id: 18,
    project_id: 1,
    title: "Update authentication documentation",
    description: "Document all authentication flows and API endpoints",
    task_type: "task",
    board_status: "backlog",
    priority: "low",
    story_points: 2,
    labels: ["documentation", "authentication"],
    acceptance_criteria: ["All flows documented", "API reference complete", "Examples provided"],
    created_at: "2024-01-22T09:00:00Z",
    updated_at: "2024-01-22T09:00:00Z",
  },
]

// =============================================================================
// Helper functions
// =============================================================================

export function getMockProject(id: number): Project | undefined {
  return mockProjects.find((p) => p.id === id)
}

export function getMockProtocol(id: number): ProtocolRun | undefined {
  return mockProtocols.find((p) => p.id === id)
}

export function getMockProtocolsByProject(projectId: number): ProtocolRun[] {
  return mockProtocols.filter((p) => p.project_id === projectId)
}

export function getMockStepsByProtocol(protocolId: number): StepRun[] {
  return mockSteps.filter((s) => s.protocol_run_id === protocolId)
}

export function getMockRunsByProtocol(protocolId: number): CodexRun[] {
  return mockRuns.filter((r) => r.protocol_run_id === protocolId)
}

export function getMockEventsByProtocol(protocolId: number): Event[] {
  return mockEvents.filter((e) => e.protocol_run_id === protocolId)
}

export function getMockClarificationsByProject(projectId: number): Clarification[] {
  return mockClarifications.filter((c) => c.project_id === projectId)
}

export function getMockClarificationsByProtocol(protocolId: number): Clarification[] {
  return mockClarifications.filter((c) => c.protocol_run_id === protocolId)
}

export function getMockSprintsByProject(projectId: number): Sprint[] {
  return mockSprints.filter((s) => s.project_id === projectId)
}

export function getMockSprint(id: number): Sprint | undefined {
  return mockSprints.find((s) => s.id === id)
}

export function getMockTasksBySprint(sprintId: number): AgileTask[] {
  return mockAgileTasks.filter((t) => t.sprint_id === sprintId)
}

export function getMockTasksByProject(projectId: number): AgileTask[] {
  return mockAgileTasks.filter((t) => t.project_id === projectId)
}

export function getMockTask(id: number): AgileTask | undefined {
  return mockAgileTasks.find((t) => t.id === id)
}
